#+TITLE: TODOs

* Package switches
** Exchange perspectives with tab-bar-mode and tabspaces
** Exchange hydra with transient

* Exchange hydra with transient

* Slides improvements
** Code in headings should be as large as non-code letters
** In normal mode the cursor should not blink
** in presentation mode we should not see property annotations
e.g.
#+begin_src emacs-lisp
:PROPERTIES:
:CUSTOM_ID: bla
:END:
#+end_src

* User-experience
** In dired, be able to start a shell (e.g. Konsole) in the current directory

* Evil-mode: improve line numbering
Show relative line numbers only in insert mode, possibly after started to type

* Presentations
** make lsp work (showing errors and suggestions) when compiling file with rust-script
** make this also work inside babel in org-mode

* TODOS and workflow
I want to have one file per project. This file includes one caption per ticket I work on, subcaptions are todos.
- When I decide to work on one todo, there is a special key to add this caption into my journal file for today, only the caption and a link to the caption in this document.
- When I finish this todo, I set it to done in the project-file. Then automatically  journal entry is added for today or if it already exists its state is set to done.
- At the end of the day I check what I finished, and get rid of all "TODO" for today

* Interesting packages
** eat for terminal-emulation
can also use eat inside eshell
** denote for note-taking
** claude code
https://systemcrafters.net/live-streams/august-22-2025/
